1024pix/pix-site

app/router.js
app/routes/stats.js
app/styles/_pages.scss
app/styles/pages/_stats-page.scss
app/templates/components/app-footer.hbs
app/templates/stats.hbs
config/optional-features.json
package-lock.json
package.json
tests/unit/routes/stats-test.js

Ajout de la page /stats

---

app/helpers/web-snippet.js
app/templates/components/news-item-post.hbs
tests/integration/helpers/web-snippet-test.js

Il manquait la possibilité d'ajouter directement du code dans Prismic.
- Ajout du helper web-snippet

[FEATURE] Ajout d'un Web snippet dans Prismic.

---

package-lock.json
package.json

Linter pas assez complet
Ajout des packages `eslint`

[TECH] Ajout de package manquant au linter. 

---

.github/pull_request_template.md

Devoir faire un copier/coller entre deux pull request pour avoir le même format (Problème / Solution / Remarques) 
Ajouter un fichier de template pour les pull request

[FEATURE] Création d'un fichier de template pour les pull request. 

---

app/templates/school-education.hbs

La team communication a demandé de changer du texte dans la page enseignement scolaire.
Changer le texte.

[FEATURE] Changement de texte sur la page enseignement scolaire (site-13). 

---

package-lock.json
package.json
scripts/git-hook/prepend-commit-message.js

Il est difficile de retrouver à quel ticket JIRA correspond un commit.
- Ajout de `husky` 
- Ajout d'un script pour créer le préfix de commit

[FEATURE] Ajout des tags Jira sur les commits (site-11).

---

app/styles/components/_burger-menu-nav.scss

La liste du burger menu affiché une version stylisé.
Enlever le style de cette liste. 
Pourquoi ne pas faire d'abord faire un style non stylisé et styliser quand on en a besoin ?

[BUGFIX] Problème d'affichage de la liste dans le burger menu (site-16).

---

app/styles/components/_multiple-column.scss
app/styles/components/_news-item-post.scss

Le métier a besoin de styliser le texte des actualités dans Prismic. 
Ajout de class css pour styliser le texte.

[FEATURE] Ajout de class dans le css pour pouvoir styliser le texte sur Prismic (site-15).

---

app/templates/components/slices/rich-text.hbs

Lorsqu'un texte était rédigé sur Prismic la mise en forme n'est pas conservé.
Garder la mise en forme faites sur Prismic.

[FEATURE] Ajout du formatage de texte directement depuis Prismic (site-21).

---

.github/pull_request_template.md

Il est difficile de trouver le lien de la review app. 
Ajouter le lien de la review app dans le template de pull request.

[TECH] Ajout de la review app dans le template de Pull Request (site-24).

---

app/styles/components/_hot-news-banner.scss

Lors de l'affichage du hot news si un lien existe dans celle-ci, son style ne permets pas de le mettre en avant. 
Ajouter du style aux liens dans les hot-news afin qu'ils puissent mieux ressortir.

[FEATURE] Possibilité d'ajouter des liens dans les hot-news (site-46).

---

app/styles/pages/_school-education.scss
app/templates/school-education.hbs

Le nombre de demande de suppport pour ouvrir un espace Pix Orga augmente, cela signifie que l'utilisateur ne voit pas la rubrique dédiée à cet effet.
- Ajouter un bouton permettant d'aller directement à cette rubrique. 
- Modifications de textes.

[FEATURE] Ajout d'un bouton sur la page enseignement scolaire (site-53).

---

app/styles/globals/_breakpoints.scss
app/styles/globals/_burger-menu.scss

Lorsqu'un utilisateur souhaite aller sur le site depuis un iPad celui-ci voit une page blanche.
Désactiver l'affichage du burger menu sous iPad.

[BUGFIX] Problème de page blanche sur iPad.

---

pages/higher-education.vue
pages/school-education.vue

Problème d'affichage sur mobile des chiffres clés. 
Passer le display flex en mode colonne sur mobile.

[BUGFIX] Problème de responsive sur les chiffres clés des pages enseignement

---

assets/scss/pages/_digital-mediation.scss
pages/about.vue
pages/digital-mediation.vue
pages/higher-education.vue
pages/school-education.vue

Certaines pages ne s'affichaient pas correctement sur mobile. 
Résoudre les problèmes de css afin qu'elles s'affichent bien sur mobile.

[BUGFIC] Résolution de problème de responsive sur certaines pages.

---

pages/employers.vue

Lorsqu'un utilisateur navigue de la page index à la page employeurs et revient sur la page index. Cette dernière se retrouve dégradé.
Mettre les class css dans le scope de la page employeurs : 
```
.employers {
.hero-banner {}
...
}
```

[BUGFIX] Problème d'affichage sur la page index après avoir été sur la page employeurs.

---

components/formable-page.vue
pages/formable-pages/contact-digital-mediation.vue
pages/formable-pages/higher-education-establishment-registration.vue
pages/formable-pages/pix-certification-application.vue
pages/formable-pages/pix-orga-higher-school-registration.vue
pages/formable-pages/pix-orga-registration.vue

Depuis le passage en v2 du site les utilisateurs ne peuvent plus voir les formulaires. 
La solution pour l'instant est de passé en iframe afin de débloquer le problème.

[BUGFIX] Problème d'affichage des formulaires

---

pages/employers.vue
services/document-fetcher.js
tests/services/document-fetcher.test.js

Ajout de la section Distributeurs sur la page Employeurs.
La section Distributeurs possèdent plusieurs cartes pour présenter les distributeurs.
- Modification de l'appel aux informations Employeurs, pour récupérer aussi les informations des sous-éléments des distributeurs
https://pix-site-integration-pr.scalingo.io

[FEATURE] Ajout de la section distributeur dans Employeurs (PS-1).

---

components/slices/img-text-column.vue
pages/index.vue

Actuel, le bloc démo de la homepage ressemble à cela.
Sauf que nous n'avons qu'une série de 8 questions en démo. La card n'est donc pas utile.
Le nouveau design implémenté:

[FEATURE] Changement design du bloc démo (PS-5)

---

components/slices/hero-banner.vue
components/slices/video.vue
nuxt.config.js
package-lock.json
package.json
plugins/sweet-modal.js
plugins/vue-plyr.js

Il n'est pas possible d'avoir une vidéo dans la home page.
Ajout d'un bouton + lien vers vidéo dans le slice hero-banner utilisé dans la home page.
Le clic sur le bouton ouvre un player vidéo dans une modale.
https://pix-site-review-pr105.osc-fr1.scalingo.io/?token=https%3A%2F%2Fpix-site.prismic.io%2Fpreviews%2FXk6QFxEAACMAfKxI%3AXlPU7xEAACUAk_Lc%3FwebsitePreviewId%3DXRsOzBAAAFFC3iCT&documentId=XYsXbBMAACEAw3Mx

[FEATURE] Ajout vidéo sur la home page (PS-18)

---

components/burger-menu-nav.vue
components/header-nav.vue
store/index.js

Il manque les entrées Pix Pro dans le burger menu de Pix Site.
Report des changements fait dans le burger menu de Pix Pro.

[FEATURE] Add Pix Pro links in Pix Site burger menu (PS-23).

---

components/slices/hero-banner.vue
components/slices/video.vue
nuxt.config.js
package-lock.json
package.json
plugins/sweet-modal.js
plugins/vue-js-modal.js
plugins/vue-plyr.js

Sur IE:
- il est impossible de cliquer sur les boutons évènementiels (mais pas de problèmes concernant les redirections)
- la modale qui devait s'afficher sur demande reste toujours affichée (ce qui laisse une grosse zone blanche au milieu de la page d'accueil)
- Changement de plugin pour la modale : `vue-js-modal`est utilisé plutôt que `sweet-modal-vue`.
- Après investigation du problème de clic: le plugin `plyr` utilise la syntaxe ES6 non supportée par IE. La mise en place de polyfill n'a pas réussi à corrigé le problème. Nous avons alors changé le plugin `vue-plyr` pour utiliser le player vidéo natif de html.
La vidéo est désormais en autoplay dès que la modale s'ouvre.
https://pix-site-review-pr110.osc-fr1.scalingo.io/

[BUGFIX] Problèmes de modales et de player vidéo sur IE

---

pages/about.vue
pages/formable-pages/contact-digital-mediation.vue
pages/formable-pages/higher-education-establishment-registration.vue
pages/formable-pages/pix-certification-application.vue
pages/formable-pages/pix-orga-higher-school-registration.vue
pages/formable-pages/pix-orga-registration.vue
pages/higher-education.vue
pages/index.vue
pages/legal-notices.vue
pages/news/index.vue
pages/school-education.vue
pages/skills.vue
pages/stats.vue
pages/terms-of-service.vue

Pour rendre les pages plus accessibles, il faudrait leur ajouter des titres.
Ajout de titres sur chaque page du site.
Se rendre sur la RA https://pix-site-review-pr123.osc-fr1.scalingo.io/ et vérifier que chaque page a bien un titre sur la fenêtre/onglet du navigateur.

[FEATURE] Ajouter des titres aux pages (PIX-905).
