.buildpacks, ember-cli-build.js, nginx.conf, package.json
Use Nginx to serve the static site.
Exclude the Pix logo from fingerprinting so that it can be used from outside.
=> Deploy using Nginx instead of ember serve

app/app.js
Il manquait une librairie de promesse pour que Prismic puisse s'exécuter.
=> [BUGFIX] Afficher la page d'actualités sous IE.

app/helpers/handle-url.js, app/templates/components/about-nav.hbs, app/templates/components/main-nav.hbs, app/templates/components/organizations-nav.hbs, app/templates/components/ressources-nav.hbs, package-lock.json, tests/integration/helpers/handle-url-test.js
- `as-url` n'indiquait pas assez la fonction du helper.
- Les tests ne permettaient pas de comprendre non plus la fonction de celui-ci.
- Renommer le helper `as-url` en `handle-url`
- Renommer les tests
=> [BSR] Renommage du helper as-url en handle-url

app/styles/pages/_organization.scss, app/templates/higher-education.hbs
- Un lien en trop avait été supprimé 
- Le logo du ministère n'était pas centré avec le texte
- Un lien trop proche du texte
- Remettre le bouton 
- Modifier le css
=> [BUGFIX] Réajustement du contenu de la page enseignement supérieur. 

app/components/burger-menu-nav.js, app/styles/_burger-menu.scss, app/styles/components/_burger-menu-nav.scss, app/styles/components/_index.scss, app/templates/application.hbs, app/templates/components/burger-menu-nav.hbs, tests/integration/components/burger-menu-nav-test.js
Le header/footer sont devenus contribuables seulement le menu mobile non. Il pouvait donc y avoir une incohérence entre la version normale et mobile. 
Rendre le menu mobile contribuable grâce à Prismic. 
- Ajout de tags dans le document `navigation` sur Prismic : `burger-menu-top` et `burger-menu-bottom`
- Ajout d'un component `burger-menu-nav`
=> [FEATURE] Rendre le menu mobile contribuable.

app/components/slices/rich-text.js, app/templates/components/slices/rich-text.hbs, tests/integration/components/slices/rich-text-test.js
Sur Prismic nous pouvons pas ajouter du texte après des slices (ex: après deux colonnes). 
Rajouter un slice `Rich Text` permettant de rajouter du texte quand on le veut.
=> [FEATURE] Ajout d'un slice permettant d'ajouter du texte (site-17).

app/styles/components/_app-footer.scss, app/templates/components/app-footer.hbs
Le logo de Pix était trop gros dans le footer ce qui ne correspondait pas au mockup et dérangeait la navigation mobile. 
Réduire la taille du logo.
=> [BUGFIX] Problème de taille du logo dans le footer (site-19).

app/styles/_colors.scss, app/styles/components/_news-item-post.scss
Il est impossible d'écrire du texte depuis Prismic avec le jaune Pix.
Ajouter le jaune Pix et la class css permettant de l'utiliser depuis Prismic.
=> [FEATURE] Ajout du jaune Pix et utilisable depuis Prismic (site-22).

app/components/slices/multiple-column.js, app/styles/components/_multiple-column.scss, app/templates/components/slices/multiple-column.hbs, tests/integration/components/slices/multiple-column-test.js
Sur Prismic, il est possible de créer des colonnes avec du textes et une image, seulement quand l'image est plus longue que le texte cela ne rends pas très bien.
Ajout de la possibilité de pouvoir centrer le texte verticalement par rapport à une autre colonne.
=> [FEATURE] Ajout de la possibilité de centrer le texte verticalement par rapport à une colonne sur Prismic (site-20).

app/routes/news/show.js, tests/acceptance/news-test.js
Lorsqu'un utilisateurs saisie une url de type : `/actualites/slug-non-existant` celui-ci voit la page d'une actualité mais vide.
Rediriger l'utilisateur vers la page `/index` lorsqu'il va sur une actualité non existante.
[https://pix-site-integration-pr54.scalingo.io](url)
=> [FEATURE] Ajout de la redirection lorsque le slug d'une actualité n'est pas bon (site-23).

app/routes/application.js, app/styles/_pages.scss, app/styles/pages/_application-error.scss, app/templates/application-error.hbs
Aujourd'hui, si Prismic tombe nous affichons un site dégradé, on a plus de header ni footer et il manquerait certains contenus. 
Ajouter une page d'erreur.
Pour afficher l'erreur dans la review App j'ai modifié les variables d'environnement sur Scalingo.
https://pix-site-integration-pr59.scalingo.io
=> [FEATURE] Ajout d'une page d'erreur (site-14).

app/templates/components/news-item-card.hbs, app/templates/components/news-item-post.hbs, tests/index.html, tests/integration/components/news-item-card-test.js, tests/integration/components/news-item-post-test.js
Quand une actualité est modifié, celle-ci reprend la date de modification et par conséquent n'affiche plus la date de création.
Afficher la date de première publication.
https://pix-site-integration-pr58.scalingo.io
=> [FEATURE] Affichage de la date de publication pour les actualités (site-25).

app/styles/components/_multiple-column.scss
Lors d'une utilisation du slice multiple-column sur prismic, le texte de la première colonne est décalé de 10px par rapport à un texte normal. Exemple  : https://pix.fr/actualites/votre-profil-evolue
Enlever ce décalage. 
https://pix-site-integration-pr60.scalingo.io
Lien de la review app pointant sur l'exemple : https://pix-site-integration-pr60.scalingo.io/actualites/votre-profil-evolue
=> [BUGFIX] Problème de marge dans le slice multiple-column (site-35).

testem.js
Depuis Chrome 76, il est impossible de lancer `npm test` sur mac.
En s'appuyant sur : https://github.com/ember-cli/ember-cli/pull/8774, on enlève `--disable-gpu` dans les différents `testem`.
`--disable-gpu ` était recommandé pour l'exécution de Chrome en headless sur Linux, mais d'après ember-cli/ember-cli#8774 il n'est plus nécessaire depuis environ 2017.
=> [TECH] Correction du crash de Chrome 76 sur Mac pendant les tests front.

app/styles/components/_news-item-card.scss, app/styles/pages/news/_index.scss, app/templates/news/index.hbs
La page `/actualites` n'est pas responsive, il est alors difficile de lire les descriptions d'actualités sur mobile. 
Rendre la page responsive.
https://pix-site-integration-pr57.scalingo.io
=> [FEATURE] Rendre responsive la page actualités (site-29).

app/styles/components/_app-footer.scss
Le logo Pix est trop grand dans le footer sur un format tablette.
Changer sa taille pour les tablettes et téléphones.
https://pix-site-integration-pr63.scalingo.io
=> [BUGFIX] Problème d'affichage du logo Pix dans le footer (site-38).

app/styles/components/_pop-in-campaigns.scss
Le texte "code parcours" n'était pas visible sous IE.
Le rendre visible sous IE.
https://pix-site-integration-pr66.scalingo.io
=> [BUGFIX] Rendre le texte "code parcours" de la pop-in rejoindre une campagne visible sous IE (site-39).

app/styles/_burger-menu.scss, app/styles/components/_pop-in-campaigns.scss
Le site n'est plus accessible depuis iOS depuis l'ajout de la pop-in "rejoindre une campagne". 
Ajout d'un `@supports` pour détecter iOS. 
https://pix-site-integration-pr69.scalingo.io
=> [BUGFIX] Problème d'affichage du site sous iOS (site-41).

app/routes/stats.js, app/styles/pages/_stats-page.scss, app/templates/stats.hbs
La page statistiques est mise à jour tous les mois. On a donc du wording à faire, une PR et mise en production pour que cette mise à jour se fasse tous les mois, c'est lourd d'un point de vue organisationnelle. 
Rendre les statistiques contribuables via Prismic.
https://pix-site-integration-pr68.scalingo.io
=> [FEATURE] Rendre contribuables la page statistiques (site-28).

config/targets.js
Il est impossible de voir notre avancement en local car le build development n'inclut pas IE.
Ajouter IE aux browsers dans `target.js`
https://pix-site-integration-pr67.scalingo.io
=> [TECH] Problème de build pour développer avec IE (site-40).

app/styles/_burger-menu.scss
La page actualité ne prends plus toute la largeur sous mobile.
Ajout d'un `width: 100%`
https://pix-site-integration-pr70.scalingo.io
=> [BUGFIX] Problème de largeur de la page actualités (site-42).

app/services/prismic.js, app/templates/components/news-item-card.hbs, app/templates/components/news-item-post.hbs, tests/integration/components/news-item-card-test.js, tests/integration/components/news-item-post-test.js
Aujourd'hui, la date affichée représente la date de première publication, seulement il est nécessaire de pouvoir choisir la date qui sera affiché, pour par exemple faire remonter une actualité etc.
Ajout d'un attribut date sur Prismic, et gérer ce nouvel attribut.
https://pix-site-integration-pr65.scalingo.io
=> [FEATURE] Possibilité de choisir la date affichée d'une actualité sur Prismic  (site-37).

app/components/hot-news-banner.js, app/routes/application.js, app/services/hot-news.js, app/services/prismic.js, app/styles/components/_hot-news-banner.scss, app/styles/components/_index.scss, app/templates/application.hbs, app/templates/components/hot-news-banner.hbs, tests/integration/components/hot-news-banner-test.js, tests/unit/services/hot-news-test.js
Lorsqu'il y a un soucis avec des services de Pix, les utilisateurs n'ont pas de visuel sur le problème sauf grâce à la page : https://status.pix.fr. On souhaite donc ajouter de la visibilité sur les problèmes sur https://pix.fr 
Ajout d'une bannière sur le site https://pix.fr, pour prévenir l'utilisateur des problèmes qu'il peut y avoir.
http://pix-site-integration-pr44.scalingo.io
=> [FEATURE] Ajout d'une bannière pour indiquer le status des applications (site-9). 

app/components/ember-chart.js
On affiche des graphiques dont l'origine est choisie automatiquement par chart.js. Cependant, cela tronque la pertinence des données.
Commencer l'origine de l'axe Y par 0. 
https://pix-site-integration-pr71.scalingo.io
=> [FEATURE] Commencer l'origine des axes Y par 0 (site-45).

tests/unit/services/hot-news-test.js
Lorsque la page hot-news n'est pas publié sur Prismic, le test du service ne fonctionnait plus.
Stuber le service de Prismic dans le test du service hot-news
=> [TECH] Ajout d'un stub pour le test du service hot-news.

app/components/handle-link.js, app/templates/components/handle-link.hbs, tests/integration/components/handle-link-test.js
Les liens pointant vers un document dans le header et footer ne fonctionnent plus et nous retournent sur la page index. 
Gérer les documents dans le composant `handle-link` pour gérer le cas du pathname `/documents/uid`
=> [BUGFIX] Problème pour les liens pix pointant sur un document (site-54).

app/components/handle-link.js, app/templates/components/handle-link.hbs
On observe une page blanche sous IE. 
Lors de la précédente PR https://github.com/1024pix/pix-site/pull/76, il a été utlisé `includes`, qui fait parti de ES6, hors IE est incompatible avec celui-ci, on utilise donc à la place `indexOf`.
Un BSR a été fait pour faire apparaître le besoin métier dans le code.
=> [BUGFIX] Problème de page blanche sous IE (site-55).

lang/en-gb.js, lang/fr-fr.js, nuxt.config.js, pages/about.vue, pages/digital-mediation.vue, pages/employers.vue, pages/formable-pages/contact-digital-mediation.vue, pages/formable-pages/higher-education-establishment-registration.vue, pages/formable-pages/pix-certification-application.vue, pages/formable-pages/pix-orga-higher-school-registration.vue, pages/formable-pages/pix-orga-registration.vue, pages/higher-education.vue, pages/legal-notices.vue, pages/news/_slug.vue, pages/news/index.vue, pages/school-education.vue, pages/skills.vue, pages/stats.vue, pages/terms-of-service.vue, plugins/link-resolver.js
Pour faciliter la migration vers Nuxt, on a mis en place `fr-be` comme language par défault, maintenant que la migration est finie, il faut remettre `fr-fr` comme language par default.
Supprimer `fr-be` comme language par défaut et comme langue.
=> [TECH] Remise en place de fr-fr comme language par défault

pages/index.vue
Le lien "Commencer" des tests de démo était généré avec le HTML suivant :
<a href="function link() { [native code] }" target="pix_app">
Commencer
</a>
ce qui ne fonctionnait pas bien sûr.
On utilise `item.card_button_link.url` et non `item.card_button_link.url.link` qui faisait référence à une fonction `link()` non pertinente ici.
=> [BUGFIX] Correction du lien vers les tests de démo (#84).

components/burger-menu-nav.vue
Le burger menu est trop décalé vers la droite et les éléments du menu du bas sont trop collés
Résoudre les problèmes sass et d'héritage des composants de vue 
Et ajout d'un `margin-top: 10px` pour les élements du menu du bas dans le burger menu.
=> [BUGFIX] Problèmes d'affichage du burger menu. 

scalingo.json
Par défaut Scalingo crée les _review apps_ avec une taille de conteneur `M` alors qu'une taille `S` est suffisante.
Avec le fichier `scalingo.json` on peut spécifier la taille par défaut des conteneurs.
=> [TECH] Création d'un fichier scalingo.json pour dimensionner les review apps

components/slices/section-column.vue
On peut avoir une 404, qui affiche un logo d'image sur la page, lorsqu'on ne met pas d'image sur Prismic mais que le slice `section-column` en cherche quand même une.  
Ajout d'une condition pour afficher l'image seulement quand il y en a une.
=> [BUGFIX] Problème d'images dans certaines sections. 

pages/school-education.vue
Certaines images provenant de prismic sur mobile sont collées à gauche
Ajouter un text-align: center pour centrer les images.
=> [BUGFIX] Certaines images sur mobile sont collées à gauche.

middleware/redirect-to-external-link.js, pages/help.vue
Certains liens externe à `https//pix.fr` pointe vers `https://pix.fr/aide` qui a été remplacé par le support de Pix : `https://support.pix.fr`, les utilisateurs se retrouvent alors sur une page oups et sont donc perdus sur le site. 
Ajouter une page help `/aide` en `fr-fr` 
Ajout d'un middleware `redirect-to-external-link` qui dans le cas de la page `help` redirige vers `https://support.pix.fr`
=> [FEATURE] Ajout d'une page /aide pour rediriger vers le support de Pix.

assets/scss/pages/_pages.scss, pages/_simple-page.vue, pages/terms-of-service.vue, services/document-fetcher.js
Lien vers https://pix.fr/dp-formulaire-demande-agrement KO
Ce lien est accessible depuis le formulaire de demande d'agrément : https://pix.fr/formulaire/demande-agrement-centre-certification (tout en bas de page en cliquant sur "lien")
Ajout de la gestion des documents `simple page` provenant de Prismic. 
Pour cela on gère les URI de type `pix.fr/:uid` dans la nouvelle page : `simple-page`.
Les documents affichés dans le site vitrine pix sont accessibles via une URI, fournie par le CMS prismic. 
Par exemple, pour la page qui ne fonctionnait plus, son URI est : `dp-formulaire-demande-agrement` (le rendu du doc peut être vu sur prismic https://pix-site.prismic.io/documents~k=simple_page&b=working&c=published&l=fr-fr/XQJW-xIAACAAYmsk*XWvliRAAACIAVfj8/)
Rendu : …
=> [BUGFIX] Lien vers un doc certif KO (PS-2)

assets/scss/components/_app-navbar.scss, components/main-nav.vue
Les utilisateurs n'ont pas tous le réflexe de cliquer sur le logo pour revenir à l'accueil.
Ajouter une entrée accueil dans la navigation principale.
Vous pouvez tester le menu avec l'entrée "Accueil" en ajoutant /en-gb dans l'url.
J'ai aussi amélioré le markup de la navigation pour passer de : 
```html
<a>
<div>
<p>
Accueil
</p>
</div>
</a>
```
à : 
```html
<a>
</a>
```
=> [FEATURE] Rajoute une entrée accueil dans la navigation (PS-11).

components/burger-menu-nav.vue
Les entrées du burger menu se superpose sur Iphone 5.
J'ai fixé la hauteur du menu pour que les deux parties ne se superposent plus.
=> [BUGFIX] Corrige le bug de superposition dans le burger menu (PS-19).

assets/scss/components/_main-nav.scss, assets/scss/globals/_colors.scss, components/main-nav.vue
Le lien vers Pix Pro doit disposer d'un séparateur à gauche.
Ajout d'une bordure à gauche du lien vers Pix Pro
Pour tester il faut cloner le repo et lancer la commande `npm run dev`. Ouvrez ensuite le site en ajoutant `/en-gb` à l'url.
=> [FEATURE] Ajout du style pour le lien vers pro.pix.fr (PS-14).

assets/scss/components/_app-navbar.scss, assets/scss/globals/_breakpoints.scss, assets/scss/globals/_globals.scss, components/burger-menu-nav.vue, components/header-nav.vue
Le burger menu n'est présent que sur la version mobile de pix-site. Sur tablette l'affichage de la navigation desktop n'est pas optimale.
Nous affichons la navigation mobile aussi sur tablette.
J'ai ajouté un breakpoint pour desktop.
=> [FEATURE] Changer le breakpoint pour l’affichage du burger menu (PS-13).

components/slices/video.vue, lang/en-gb.js, lang/fr-fr.js, layouts/error.vue
L'utilisateur qui tombait sur une page qui n'existait pas n'avait pas de moyen facile de revenir à l'accueil.
- Changer le texte quand l'erreur est une 404.
- La première solution fut de faire une redirection automatique. Malheureusement, la page Error.vue est un layout avec peu de fonctionnalité : pas de `fetch` ou de `asyncData`, impossibilité de savoir qu'on vient de la page `error.vue`quand on est dans un middleware. Donc pour l'instant on met de coté cette solution.
- Ajout de quelques améliorations d'A11Y de cette page.
Aller sur : https://pix-site-review-pr111.osc-fr1.scalingo.io/aide/certifications
https://pix-site-review-pr111.osc-fr1.scalingo.io/
=> [FEATURE] Changement de texte pour la page d'erreur (PS-34).

components/burger-menu-nav.vue
- Quand il y a des Hot News, le bouton du burger menu s'affichait par dessus et n'était pas visible.
- La position du bouton est dans le code du plugin du burger-menu
- Le code du bouton indiquant une `position: absolute` avec un `top`fixe, j'ai dû passer au dessus en précisant la classe `.nav .bm-burger-button`(qui a plus de poids que juste `.bm-burger-button` pour le rendre en position relative, avec un top différent (lié au contexte) et un `margin-bottom` negatif  pour que la hauteur du bouton n'empiète pas sur le reste de la navigation
- Il faudrait revoir tout le squelette de la navigation pour que le bouton soit bien aligné dans la navigation
- Ces modifications sont aussi à faire dans pix-site-pro : https://github.com/1024pix/pix-site-pro/pull/9 …
=> [BUGFIX] Le bouton du burger-menu s'affichait sur les hot news (PS-36).

components/hot-news-banner.vue
- La croix pour fermer le bandeau des nouvelles ne fonctionnait pas
- Pour savoir si on l'affichait, on se basait sur la présence d'une `hotnews` et on mettait la variable 
`isOpen` a false une fois fermée.
- Séparation de la div permettant de savoir s'il y a une news et de celle pour savoir si l'utilisateur a fermé ou non.
- Faire la même chose sur pix-site-pro : https://github.com/1024pix/pix-site-pro/pull/10
https://pix-site-review-pr113.osc-fr1.scalingo.io/
=> [BUGFIX] Pouvoir fermer le bandeau des hot news (PS-37).

README.md, components/pix-link.vue, config/locale-domains.js, lang/fr.js, middleware/current-page-path.js, nuxt.config.js, package-lock.json, package.json, plugins/link-resolver.js, store/index.js
Le site actuel est le même quelque soit le domaine ou la langue.
Le plugin `nuxt-i18n` permet de configurer un domaine différent par locale.
Il est choisi d'utiliser pix.org pour la locale `fr` (French dans prismic) et pix.fr pour la locale `fr-fr` (Français - France dans prismic).
Cette PR ne s'occupe que de la mise en place des deux domaines.
Le contenu et la structure des deux sites feront l'objet de nouvelles PR.
https://site-pr115.review.pix.fr
et
https://site-pr115.review.pix.org
=> [FEATURE] Gestion de pix.org et pix.fr (PIX-629).

components/header-nav.vue
Ne pas afficher la marianne sur le site .org
Dans header-nav, vérifier la locale et afficher la marianne seulement si 'fr-fr'
https://site-pr116.review.pix.fr/
https://site-pr116.review.pix.org/
=> [FEATURE] Afficher la marianne que pour le site franco-français (PIX-667).

components/organization-nav.vue
- Retirer "Enseignement supérieur"
- Retirer "Enseignement scolaire"
- Retirer "Devenir centre de certification"
- Sur Prismic, retirer ces éléments de la page lorsque l'on est sur `.org`
- La suppression des liens laisse un bandeau gris vide: dans cette PR, ce bandeau est supprimé s'il est vide
https://site-pr117.review.pix.fr/
https://site-pr117.review.pix.org/
=> [FEATURE] Retirer des liens du site .org (PIX-702)

pages/index.vue
Le nombre d'élément dans la partie Le projet Pix sur la home est différent entre pix.fr et pix.org. Le style CSS pour 5 éléments ne rend pas bien avec 6 éléments
- Cette partie est gérer en flex, de base avec 20% de la largeur pour chaque item, donc les 5.
- Cette largeur est passé à 33%, pour afficher 3 items par ligne (donc pour 6, 2 lignes de 3 items)
- Dans le cas des 5 items, le width passe à 20% comme avant.
Dans le CSS, l'utilisation de `__item:nth-child(1):nth-last-child(5)` permet de choisir l'item qui est le premier de la liste, et le 5eme en partant de la fin, donc le 1er item d'une liste de 5. Cela permet de mettre le CSS que sur les items d'une liste de 5.
https://site-pr118.review.pix.fr/ avec 5 éléments
https://site-pr118.review.pix.org/ avec 6 éléments
=> [FEATURE] Pouvoir afficher 6 éléments dans les items de la home (PIX-705).

pages/index.vue
Les images de la page d'accueil sont étirées sur IE.
Utiliser des images svg qui ont toutes la même hauteur.
Spécifier cette hauteur dans le css.
RAS
https://site-pr120.review.pix.org/
=> [BUGFIX] Adapter la taille des icones de la home (PIX-742).

components/burger-menu-nav.vue
Contexte Sur les sites vitrine, lorsqu'on regarde les headers, le premier que l'on a est un H3 pour le lien vers Pix-pro.
Remplacer le H3 par un P
=> [BUGFIX] Le texte Pix Pro a un titre alors que ce n'en ait pas un (PIX-873).

nuxt.config.js
Pour l'accessiblité, on a besoin de rajouter un tag indiquant la langue dans laquelle la page est rédigée.
Ajouter un attribut `lang` sur le tag `html`
Pour l'instant,  on a que `fr`, donc il est en dur. Quand on en saura davantage sur comment on décide de la langue de la page, il faudra rendre cette valeur dynamique.
https://pix-site-integration-pr.scalingo.io
Ouvrir la console, inspecter la page et voir l'attribut `lang="fr"` sur la balise html.
=> [FEATURE] Ajouter l'attribut lang (PIX-833).
